export const SUPABASE_URL = "https://jkenultexkujajrdnqsy.supabase.co";
export const SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImprZW51bHRleGt1amFqcmRucXN5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM2OTEwMjQsImV4cCI6MjA4OTI2NzAyNH0.28yqUN6ym5n9HPiQovLneZCvCnzg7El3famWrYoiE4U";
